### ISSUE TITLE
Does the #[dependency] attribute macro need return type?

### ISSUE THREAD

**Issue by Eveheeero** [Migorithm/ruva#31]
For now, return type must be needed cause of https://github.com/BeringLab/event-driven-library/blob/de4d3043f63f8a7e25fc017b89c3650155648b9c/event-driven-macro/src/dependency.rs#L8 scoped to type.
In main document, it was not needed for \#[dependency] macro
Does it intended?

**Comment by Migorithm** [comment]
Oh, actually more often than not, return type would be specified. I guess I made a wrong example. 

With that said though, it'd be great if it allows also for non-returning function too.
