### ISSUE TITLE
New way to get dependency from #[dependency] function

### ISSUE THREAD

**Issue by Eveheeero** [Migorithm/ruva#34]
지금 현재 구현은 dependency객체는 항상 (매크로에 따르면) `crate::dependencies::Dependency`의 `impl`블럭을 통해 얻고 있습니다.

해당 방법은 `crate::dependencies`를 항상 참조하고 있기 때문에, 이미 해당 모듈 경로를 사용하고 있다면 현 라이브러리의 사용이 힘들 수 있습니다.

해당 방법보다, `Fn<() -> dyn Pin<Box<T>>`에 대한 함수 포인터를 받아 dependency 객체를 주입하는 방법은 어떨까요?

**Comment by Migorithm** [comment]
The issue has been discussed and moved to https://github.com/BeringLab/event-driven-library/issues/55
