### ISSUE TITLE
Does begin call needed when initializing UOW?

### ISSUE THREAD

**Issue by Eveheeero** [Migorithm/ruva#46]
According down, the recording transaction is called when calling `UnitOfWork::new()`.
https://github.com/BeringLab/event-driven-library/blob/fe74159196e67c5bb6dea2a65e5b0137d18fd2d6/event-driven-core/src/unit_of_work.rs#L139

I believe that the UOW flow should be of the form `begin() -> commit()` or `begin() -> commit()`

However, call `begin` inside of `UOW::new()` does not require the user to call `begin`, and I believe the definition conflicts with `pub fn begin(&self)`

I think one of these should go away, and if it does, I think it should be a `begin` call in initialization.

Is my thinking correct?

**Comment by Migorithm** [comment]
Yeah pretty much. 

My understanding is, initialization of UOW must be the same as beginning transaction. Hence, I thought having to invoke two methods at caller site may be redundant.

**Comment by Eveheeero** [comment]
resolved in https://github.com/BeringLab/event-driven-library/commit/29d81d394472d84a4fdfb27f365890167adf367f
